nombre = " abraham hernandez "
print(nombre.upper())
print(nombre.lower())
print(nombre.strip().capitalize())
print(nombre.strip().title())
print(nombre.strip())
print(nombre.find("br"))
print(nombre.strip().title().replace("ernandez", "dez"))
print("br" in nombre)
print("br" not in nombre)
